// Code generated by sails-client-gen-v2. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct AgeLensClientProgram;

impl AgeLensClientProgram {
    pub const ROUTE_ID_AGE_LENS: u8 = 1;
}

impl sails_rs::client::Program for AgeLensClientProgram {}

pub trait AgeLensClient {
    type Env: sails_rs::client::GearEnv;
    fn age_lens(&self) -> sails_rs::client::Service<age_lens::AgeLensImpl, Self::Env>;
}

impl<E: sails_rs::client::GearEnv> AgeLensClient
    for sails_rs::client::Actor<AgeLensClientProgram, E>
{
    type Env = E;
    fn age_lens(&self) -> sails_rs::client::Service<age_lens::AgeLensImpl, Self::Env> {
        self.service(AgeLensClientProgram::ROUTE_ID_AGE_LENS)
    }
}
pub trait AgeLensClientCtors {
    type Env: sails_rs::client::GearEnv;
    #[allow(clippy::new_ret_no_self)]
    #[allow(clippy::wrong_self_convention)]
    fn new(self) -> sails_rs::client::PendingCtor<AgeLensClientProgram, io::New, Self::Env>;
}

impl<E: sails_rs::client::GearEnv> AgeLensClientCtors
    for sails_rs::client::Deployment<AgeLensClientProgram, E>
{
    type Env = E;
    fn new(self) -> sails_rs::client::PendingCtor<AgeLensClientProgram, io::New, Self::Env> {
        self.pending_ctor(())
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(New () -> (), 0);
}

pub mod age_lens {
    use super::*;

    #[sails_rs::sails_type(crate = sails_rs)]
    #[derive(PartialEq, Clone, Debug)]
    pub enum AgeBand {
        Child,
        Teen,
        Adult,
        Senior,
    }
    #[sails_rs::sails_type(crate = sails_rs)]
    #[derive(PartialEq, Clone, Debug)]
    pub struct AgeReport {
        pub years: u16,
        pub months_since_birthday: u8,
        pub days_alive: u32,
        pub days_until_next_birthday: u16,
        pub age_band: AgeBand,
        pub is_birthday_today: bool,
    }
    #[sails_rs::sails_type(crate = sails_rs)]
    #[derive(PartialEq, Clone, Debug)]
    pub struct Date {
        pub year: u16,
        pub month: u8,
        pub day: u8,
    }
    #[sails_rs::sails_type(crate = sails_rs)]
    #[derive(PartialEq, Clone, Debug)]
    pub struct DaysThresholdReport {
        pub eligible: bool,
        pub days_alive: u32,
        pub minimum_days: u32,
        pub reason: EligibilityReason,
    }
    #[sails_rs::sails_type(crate = sails_rs)]
    #[derive(PartialEq, Clone, Debug)]
    pub enum EligibilityReason {
        AgeAtOrAboveThreshold,
        AgeBelowThreshold,
    }
    #[sails_rs::sails_type(crate = sails_rs)]
    #[derive(PartialEq, Clone, Debug)]
    pub struct ThresholdReport {
        pub eligible: bool,
        pub years: u16,
        pub minimum_age: u16,
        pub reason: EligibilityReason,
    }

    pub trait AgeLens {
        type Env: sails_rs::client::GearEnv;
        fn calculate_age(
            &self,
            birth_date: Date,
            as_of_date: Date,
        ) -> sails_rs::client::PendingCall<io::CalculateAge, Self::Env>;
        fn check_age_days_threshold(
            &self,
            birth_date: Date,
            as_of_date: Date,
            minimum_days: u32,
        ) -> sails_rs::client::PendingCall<io::CheckAgeDaysThreshold, Self::Env>;
        fn check_age_threshold(
            &self,
            birth_date: Date,
            as_of_date: Date,
            minimum_age: u16,
        ) -> sails_rs::client::PendingCall<io::CheckAgeThreshold, Self::Env>;
        fn version(&self) -> sails_rs::client::PendingCall<io::Version, Self::Env>;
    }

    pub struct AgeLensImpl;

    impl sails_rs::client::Identifiable for AgeLensImpl {
        const INTERFACE_ID: sails_rs::InterfaceId =
            sails_rs::InterfaceId::from_bytes_8([120, 37, 84, 206, 176, 193, 214, 35]);
    }

    impl<E: sails_rs::client::GearEnv> AgeLens for sails_rs::client::Service<AgeLensImpl, E> {
        type Env = E;
        fn calculate_age(
            &self,
            birth_date: Date,
            as_of_date: Date,
        ) -> sails_rs::client::PendingCall<io::CalculateAge, Self::Env> {
            self.pending_call((birth_date, as_of_date))
        }
        fn check_age_days_threshold(
            &self,
            birth_date: Date,
            as_of_date: Date,
            minimum_days: u32,
        ) -> sails_rs::client::PendingCall<io::CheckAgeDaysThreshold, Self::Env> {
            self.pending_call((birth_date, as_of_date, minimum_days))
        }
        fn check_age_threshold(
            &self,
            birth_date: Date,
            as_of_date: Date,
            minimum_age: u16,
        ) -> sails_rs::client::PendingCall<io::CheckAgeThreshold, Self::Env> {
            self.pending_call((birth_date, as_of_date, minimum_age))
        }
        fn version(&self) -> sails_rs::client::PendingCall<io::Version, Self::Env> {
            self.pending_call(())
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(CalculateAge (birth_date: super::Date, as_of_date: super::Date) -> super::AgeReport | String, 0, <super::AgeLensImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(CheckAgeDaysThreshold (birth_date: super::Date, as_of_date: super::Date, minimum_days: u32) -> super::DaysThresholdReport | String, 1, <super::AgeLensImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(CheckAgeThreshold (birth_date: super::Date, as_of_date: super::Date, minimum_age: u16) -> super::ThresholdReport | String, 2, <super::AgeLensImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Version () -> String, 3, <super::AgeLensImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
    }
}
